### PR TITLE
Update to 0.10.2, added logrotate, change url and fail2ban

### LINKED ISSUE #35: Update to version 0.10.2
App needs love to get to the version 0.10.2.

Someone care to update?

### PR DESCRIPTION
**Pull request by lapineige**
## Problem
- The app is not up to date with the upstream.Fix #35

## Solution
- Update the package

## PR Status
- [x] Code finished.
- [x] Fix or enhancement tested.
- [x] Upgrade from last version tested.
- [x] Can be reviewed and tested.

## Validation
---
*Minor decision*
- **Upgrade previous version** : 
- [x] **Code review** : 
- [ ] **Approval (LGTM)** : 
- [ ] **Approval (LGTM)** : 

[Build Status/1/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20(Anmol)/1/)

When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by anmol26s** [comment]
@lapineige 

Sources have to be updated here: https://github.com/YunoHost-Apps/shaarli_ynh/blob/testing/conf/app.src

**Comment by lapineige** [comment]
Oh thanks for the reminder.

We need to update them even with testing versions ?

**Comment by anmol26s** [comment]
@lapineige 
Upgrade was giving warning: 
WARNING ./upgrade: line 116: [: -eq: unary operator expected
So fixed it by changing the is_public to latest Yunohost package and removed unnecessary helpers in common.sh

**Comment by anmol26s** [comment]
Can someone review the changes and test the app? 
Any help to fix check_url would be appreciated.

**Comment by anmol26s** [comment]
Have a look at YunoHost-Apps/nextcloud_ynh#138.
We need to remove php.ini and merge its content to pool file.

**Comment by anmol26s** [comment]
@lapineige @Rafi594 
Can you review and test the testing branch? The Ci is having some issues with change_url, so its failing. This can be solved after the Ci is fixed. For now this could be merged after test.

**Comment by lapineige** [comment]
Upgrade works, new features too.
I've not tested fail2ban.

Change url work, but I don't understand why we have this warning with change_url : we never use it, don't we ?

**Comment by lapineige** [comment]
LGTM :)

**Comment by lapineige** [comment]
> We need to remove php.ini and merge its content to pool file.

It seems to raise an exception during backup:
> Attention : Source path '/etc/php5/fpm/conf.d/20-shaarli.ini' does not exist

**Comment by anmol26s** [comment]
Indeed, I forgot to remove `php.ini` backup and restore commands. Thanks for the hinting that.

**Comment by lapineige** [comment]
@Rafi594 could you do an additional test (at least install and/or upgrade) ?

Then I think we can merge :)

**Comment by anmol26s** [comment]
Any update on this?

**Comment by lapineige** [comment]
@Rafi594 if you have no objection, I'm ok to merge :)

**Pull request merged**
