### PR TITLE
Fix the damn log issue

### PR DESCRIPTION
**Pull request by alexAubin**
I'm getting mad of seeing this issue popping every two days on the forum or the chat. Here's a fix that requires https://github.com/YunoHost/yunohost/pull/810

### CODE REVIEW

**Comment by lapineige** [comment]
So I need to wait until Yunohost's PR has landed ?

(finally a fix, 🙏)

**Comment by alexAubin** [comment]
Yunohost fix got released in 3.6.5.1 ... https://forum.yunohost.org/t/yunohost-3-6-release-sortie-de-yunohost-3-6/8359/61

**Comment by alexAubin** [comment]
Sooo bumped the yunohost requirement + app version, to me we're good to go

**Comment by lapineige** [comment]
When this yunohost version will be available ?

**Comment by alexAubin** [comment]
@lapineige : it is available right now

**Comment by lapineige** [comment]
Thanks a lot for your work ! 😃

**Pull request merged**
