### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- *Upgrade to version 0.12.1*
- *Fix NGINX redirections*
- *Remove pkg_dependencies*
- *Fix upgrade script*
- *reworked rights and permissions*

## PR Status
- [x] Code finished.
- [x] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Package_check results
---

[Build Status/badge/icon)](https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20PR63%20(ericgaspar)/)

### CODE REVIEW

**Comment by lapineige** [comment]
Could we fix that bug #64 as well ?
Sounds like a major issue for our users who would like to upgrade :/

**Comment by ericgaspar** [comment]
> Could we fix that bug #64 as well ?
> Sounds like a major issue for our users who would like to upgrade :/

The upgrade script, as is, reinstalls the application folder from source before copying the `data` and the `tpl` file to a temporary directory, because of that, data and settings from the previous installation are lost. :/

733cfdc should adress that issue.

I have also reworked rights and permissions (as advised in the Shaarli documentation page) as follow:
```
chown -R $app: $final_path
chmod -R g+rX $final_path
chmod -R g+rwX $final_path/{cache/,data/,pagecache/,tmp/}
```
ping: @tituspijean

**Review by tituspijean — APPROVED** [review]
LGTM.

Though, was there an issue with the Nginx "fix"?
And sorry for the oversight with the data directory. Having never used Shaarli before, I only tested it by adding a link without attachments (which only uses the database).

**Comment by lapineige** [comment]
> I have also reworked rights and permissions (as advised in the Shaarli documentation page) as follow:

@ericgaspar  Am I correct if I say that this fixes https://github.com/YunoHost-Apps/shaarli_ynh/pull/54#discussion_r410200542 ?
(and as a result, https://github.com/YunoHost-Apps/shaarli_ynh/issues/55)

**Comment by ericgaspar** [comment]
> > I have also reworked rights and permissions (as advised in the Shaarli documentation page) as follow:
> 
> @ericgaspar Am I correct if I say that this fixes [#54 (comment)](https://github.com/YunoHost-Apps/shaarli_ynh/pull/54#discussion_r410200542) ?
> (and as a result, #55)

Yes, I guess so.

**Pull request merged**
