### PR TITLE
Backup/restore scripts

### PR DESCRIPTION
**Pull request by rokaz**
Hi,

I wrote these basic backup/restore scripts. I tested them and they seem to be working as expected.

### CODE REVIEW

**Comment by lapineige** [comment]
Sorry for the delay.
I'm testing those scripts right now :)

**Comment by lapineige** [comment]
Maybe it's because of my installation, but when making a backup, removing shaarli, and restoring later, it raises and error like: `An error happened during LDAP operation`

**Comment by rokaz** [comment]
I have the same error when backing up and restoring both hooks and other official apps (tested with wallabag and dokuwiki). Backup/restore without the hooks (only the app) works on my test system (the ynh_dev script, on stable), as for the other apps and the hooks alone. I didn't take the time to talk with the ynh devs of this issue, which doesn't seem to be triggered by this only app.

**Comment by lapineige** [comment]
I did it just for shaarli app, but I don't remember if I added the hooks too.
I'll test again.

If it works, and as it seems to be a known bug, I'll merge your PR and add a warning in the README :)

**Comment by lapineige** [comment]
Ok, if I had the `--ignore-hooks` option it works. But I have a warning for Insufficient permissions in "cache" , "data", "pagecache" and"tmp/" directories.
Looking at the script, it setup the owner as root (same for the group). Shouldn't it be www-data ? (as during install)

It works like that on your config ?

**Comment by rokaz** [comment]
No, it is a mistake from myself. I pushed the correction.

**Comment by lapineige** [comment]
Everything works right now :)

**Pull request merged**
