### PR TITLE
Don't override (new) official templates with old ones

### LINKED ISSUE #65: Templates are not updated on upgrade (was: Title and descriptions fields do not autofill anymore)
### Describe the bug

When adding a link (ex: https://github.com/shaarli/Shaarli), the title and description fields are not auto-filled.

### Context

- This worked with the previous version of the package (0.10.4).
- I host it on a subdomain (b.domain.tld)
- Hardware: *Kimsufi 2G*
- YunoHost version: *4.0.8.3*
- I have access to my server: *Through SSH | through the webadmin*
- Using package version/branch: the latest available through the Yunohost update interface
- If upgrading, current package version: *0.12.1~ynh1*
- Theme: *default*

### Steps to reproduce

- Add a link, https://github.com/shaarli/Shaarli

### Expected behavior

- Field "Title" should be filled with "GitHub - shaarli/Shaarli: The personal, minimalist, super-fast, database free, bookmarking service - community repo"
- Description should be filled with "The personal, minimalist, super-fast, database free, bookmarking service - community repo - shaarli/Shaarli"

You can try on https://demo.shaarli.org/admin/shaare?post=https%3A%2F%2Fgithub.com%2Fshaarli%2FShaarli with login `demo` and password `demo`.

### Logs

I could not find any meaningful log.

### PR DESCRIPTION
**Pull request by lapineige**
Fix #65 #67

## Problem
- Templates download from official source are overridden with old version of them during upgrade 

## Solution
- don't copy old template if an official template file already exist

## PR Status
- [x] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [x] Can be reviewed and tested.

### CODE REVIEW

**Comment by lapineige** [comment]
This is blocking a lot of (old) users as current Shaarli version is not compatible with their (old) templates, so I think it's important to merge this ASAP… if someone with an old template could test this… :pray:

**Review by ericgaspar — APPROVED** [review]
You may want to merge it to testing for user to test it first?

**Comment by lapineige** [comment]
Actually I hoped that this would already be tested here 😅

**Comment by lapineige** [comment]
Just changed version number, I always forget that without this change automatic update won't be possible.

**Comment by nicofrand** [comment]
Hi, sorry I am really busy with personal things those last weeks (and following too), I didn't have time to test the MR, but this seems fine indeed!

**Comment by ericgaspar** [comment]
Is this PR ready to be merged ? 👀

**Comment by lapineige** [comment]
I can't test it myself, and I didn't have any feedback so I'm not sure… but I'm kind of willing to YOLOmerge anyway…

**Comment by alexgarel** [comment]
This problem hit me hard, for it render new version of ynh non usable.

So I advocate for this commit.

**Comment by alexgarel** [comment]
I'm voluntary to test if someone point me to some explanations on how to do it !

**Comment by lapineige** [comment]
Oh, I just realised I lost my rights to merge a PR on that repo… @YunoHost-Apps/apps-group is this linked to the fact that shaarli maintainers team was removed ?

I you're willing to test: I don't remember/know if that's possible with the web interface, sorry.
But if using the command line is ok for you, here the steps:
- make a backup: the upgrade script will do it for you too, but we never know :) (and it should be a small backup)
- as admin or root : `yunohost app upgrade shaarli -u https://github.com/YunoHost-Apps/shaarli_ynh/tree/template-override-fix-1`

Then just try to connect to shaarli.
If something bad happens, it will display a command to share the full upgrade log, please do :)

**Comment by alexgarel** [comment]
@lapineige I tried, but it did not work. 

```
yunohost app upgrade shaarli -u https://github.com/YunoHost-Apps/shaarli_
ynh/tree/template-override-fix-1
Info: Now upgrading shaarli...
Info: [+...................] > Loading installation settings...
Info: [#++.................] > Ensuring downward compatibility...
Info: [###++...............] > Backing up the app before upgrading (may take a while)...
Info: [#####+..............] > Upgrading NGINX web server configuration...
Info: [######++............] > Making sure dedicated system user exists...
Info: [########++..........] > Upgrading PHP-FPM configuration...
Info: [##########+.........] > Upgrading logrotate configuration...
Info: [###########++.......] > Securing files and directories...
Info: [#############++.....] > Reconfiguring Fail2Ban...
Info: The service fail2ban has correctly executed the action reload-or-restart.
Info: [###############+....] > Reloading NGINX web server...
Info: [################++..] > Upgrade of shaarli completed
Success! shaarli upgraded
Success! Upgrade complete
```

It seems it does not pass in the part of the script you changed. I don't get **Upgrading source files...** on the console. 

I see this is guarded by `if [ "$upgrade_type" == "UPGRADE_APP" ]`

How can I make it an UPGRADE_APP ? (sorry I don't have the time to deep dive into yunohost to understand that !).

**Comment by lapineige** [comment]
Hum, it seems that the condition is not met, but I don't understand why (and what's that condition anyway).

@Josue-T, sorry to bother you, but since you are the author of https://github.com/YunoHost/yunohost/pull/864 maybe you can't have some input here: 
- is that condition a valid check ?  https://github.com/YunoHost-Apps/shaarli_ynh/blob/54e83502257e9221cbb2ddb705d42cc070b9c750/scripts/upgrade#L68
- in which case is UPGRADE_APP going to happen ? In this case the version is different : https://github.com/YunoHost-Apps/shaarli_ynh/pull/66/files#diff-57aeb84da86cb7420dfedd8e49bc644fb799d5413d01927a0417bde753e8922f. But I'm unsure whereas it's the package version or the app version that is different.

**Comment by ericgaspar** [comment]
Let's merge to testing and test from there...

**Comment by lapineige** [comment]
In fact I was making a commit in `template-override-fix1` 😅

**Comment by lapineige** [comment]
To sum up:
1. https://github.com/YunoHost-Apps/shaarli_ynh/blob/54e83502257e9221cbb2ddb705d42cc070b9c750/scripts/upgrade#L68 `"$upgrade_type" == "UPGRADE_APP"` condition seems wrong in some cases (upgrade from same app version, but different package version). This should be fine, except for users that had this issue with `0.12.1` and try to upgrade to this branch… which is `0.12.1` too, but package version `ynh2`.
I'm not that sure about it, please correct me if needed :)
2. this was not applied during a force upgrade, and I suppose it's not applied during a force update that upgrade the app version. That is fixed by #68 

Hence, until we fix that first point, @alexgarel you should be able to upgrade with `yunohost app upgrade shaarli -u https://github.com/YunoHost-Apps/shaarli_ynh/tree/template-override-fix-1 --force` (please note the ` --force`) and get the fix.

**Pull request merged**
