### PR TITLE
Update to 0.9.6

### PR DESCRIPTION
**Pull request by mkody**
Tested with a fresh install (and with manual backup of data -> uninstall -> install -> restore data).

### CODE REVIEW

**Comment by anmol26s** [comment]
Not working on fresh install for me.

**Comment by alexAubin** [comment]
(Bump ? Is this a duplicate work of #29 ?)

**Comment by mkody** [comment]
#29 was set as "long term" with a lot of rewrite, this PR is just about bumping to the upstream version.
I'll update to 0.9.3 either today or tomorrow and re-check if the fresh install really isn't working.

**Comment by mkody** [comment]
Tested fresh install with 0.9.3, it works fine.
Backing old data, reinstalling it to 0.9.3 and restoring data also works.

**Comment by alexAubin** [comment]
Bumpity bump ? I'm not in the app team, but just randomly checking repositories and this looks like a cool app to keep up to date 👍

**Comment by Rafi594** [comment]
Hi

I'll continue the refactoring of this app and upgrade to the latest version

**Comment by Rafi594** [comment]
https://github.com/YunoHost-Apps/shaarli_ynh/pull/29

**Comment by Rafi594** [comment]
This PR will be merged in 3 days if @lapineige don't approve.

**Comment by mkody** [comment]
I might still [update it to 0.9.6](https://github.com/shaarli/Shaarli/releases/tag/v0.9.6) either later today or tomorrow.
0.9.3 is a good spot since it has the latest security fix, but [0.9.4 brought interesting features and fixes](https://github.com/shaarli/Shaarli/releases/tag/v0.9.4).

**Comment by lapineige** [comment]
Let's update directly to 0.9.6, as it doesn't introduce significant changes to the upgrade process.
(and has some cool additions indeed :)

**Comment by lapineige** [comment]
Yeah, we really need that backup script...

It works well.
Let's merge this.
It's ok for you @Rafi594 ?

**Pull request merged**
