### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by alexAubin**

### CODE REVIEW

**Comment by alexAubin** [comment]
!testme

**Comment by lapineige** [comment]
Isn't that helper supposed to work around existing files ? 😅

**Comment by alexAubin** [comment]
Yeah hmpf I remember a stupid story about how the log is supposed to end in `.log` and not `.txt` otherwise it assumes it's supposed to be a folder ~_~

**Comment by lapineige** [comment]
Naive question : what's wrong with the current syntax of the helper ? (if it work 😄)

**Comment by alexAubin** [comment]
It doesnt, the official CI shows:

```
48493 INFO [#####+++++..........] > Adding system configurations related to shaarli...
54594 WARNING /usr/share/yunohost/helpers.d/logrotate: line 63: [: -u shaarli: integer expression expected
```

and if you look at the detailed log, the parsing of the argument is completely fucked up and I very much doubt that any log rotation actually happens

**Comment by lapineige** [comment]
Ok then it's a big deal :(
Thank you :)

**Comment by alexAubin** [comment]
Issue related to `.txt` to be fixed in next core release, cf https://github.com/YunoHost/yunohost/commit/308ed0e1742f405fb2b7ce38d75b707d6dcc90e9 ...

**Comment by lapineige** [comment]
Nice !
Is it ready for CI then ? Should we update the manifest ?

**Comment by alexAubin** [comment]
Yes we should update the manifest, but the new version aint released yet

**Comment by alexAubin** [comment]
CI now runs 11.2.9 which includes a refactoring of the logrotate madness, should fix the issue

!testme

**Comment by alexAubin** [comment]
!testme

**Pull request merged**
