### PR TITLE
Backup themes during upgrade

### PR DESCRIPTION
**Pull request by lapineige**
Solves #41

### CODE REVIEW

**Comment by lapineige** [comment]
Up :)

**Comment by nicofrand** [comment]
Would love to this PR merged (my app broke again because I have a custom theme) :p

**Comment by lapineige** [comment]
Didn't you use this branch ?

**Comment by lapineige** [comment]
If you upgraded without explicitly specifying this branch, you lost the changes.

Can you upgrade again with this branch and tell me if it works ? If yes, I'll merge.

**Pull request merged**
