### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lapineige**
Merging https://github.com/YunoHost-Apps/shaarli_ynh/pull/73

### CODE REVIEW

**Comment by lapineige** [comment]
!testme

**Comment by lapineige** [comment]
@YunoHost-Apps/apps-group CI fails in a strange way :

> Error: In use
Running: yunohost app install --force /app_folder -a "domain=sub.domain.tld&path=/path&is_public=1&admin=package_checker&password=pass&title=Shaarli&"
1624 ERROR This URL is either unavailable, or conflicts with the already installed app(s):
> * sub.domain.tld/ → Shaarli (shaarli)
>
>Error: Installation failed.

Did it forget to remove the previous CI result ? :sweat_smile:

**Comment by lapineige** [comment]
!testme

**Comment by ericgaspar** [comment]
Well the CI dev is broken...

**Review by alexAubin — APPROVED** [review]

**Comment by lapineige** [comment]
Are we supposed to run the CI ? Or should we merge ?

@alexAubin what was that file by the way ?

**Comment by alexAubin** [comment]
I rescheduled the CI job in https://ci-apps-dev.yunohost.org/ci/job/3924 as it failed because of some technical bug on the CI which should be fixed now (I think ? Maybe ...)

Anyway the .DS_Store is some file automatically added by Mac I believe ;)

**Pull request merged**
