### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by lapineige**
Fix #51 #50
Thanks to @alexAubin :)

### CODE REVIEW

**Comment by alexAubin** [comment]
Since it was still not merged ... added a commit :D 

Added a build on the dev CI that should show up here ... https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/shaarli_ynh%20(aleks)/ (though dunno why my first attempt to start it failed, will see)

**Comment by lapineige** [comment]
Oh yeah, already forgot this one… which is not that old finally ^^

**Comment by lapineige** [comment]
Build fails: https://ci-apps-dev.yunohost.org/jenkins/view/aleks/job/shaarli_ynh%20(aleks)/lastBuild/console

**Comment by alexAubin** [comment]
Resubmitted it : https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20(aleks)/ 

but the dev CI is busy processing all @yalh76 's work ;P

**Comment by alexAubin** [comment]
Annnnnnd it's all green ! https://ci-apps-dev.yunohost.org/jenkins/job/shaarli_ynh%20(aleks)/lastBuild/console

**Pull request merged**
